name: Build & Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: develop
    steps:
      - uses: actions/checkout@v2
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install -g firebase-tools
      - run: firebase emulators:exec \"gradlew build\"
      - name: Deploy with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: appengineDeploy
